site_name: Stabilizing Behaviors Consultations
site_name_short: Stabilizing Behaviors
site_url: http://stabilizingbehaviors.org
site_author: Stabilizing Behaviors
copyright: Stabilizing Behaviors

# repository information
repo_url: https://github.com/almostengr/stabilizing-behaviors
repo_name: Github
remote_name: origin
remote_branch: website

# Development server details
dev_addr: 10.10.10.102:8080

# Appearance
theme:
  name: null
  custom_dir: 'sbtheme'
  language: en
  # google_tag:
  site_icon: "/images/SmallLogo250x151.png"
  main:
    bgcolor: bg-light
  reviews:
    - author: test
      date: May 2024
      comment: They offer great set of services!
  static_templates:
    - 404.html
    - 500.html

  reviews:
    - date: January 2024
      comment: Great customer service!
      name: Anonymous

  sidebar:
    - heading: Testing1
      body: this is a test for the first heading
      buttonlink: /contact
    - heading: testing2
      body: test for the second card
      buttonlink: /services
      
use_directory_urls: true
strict: false


plugins:
  # - minify:
      # minify_html: true

extra:
  generator: false
