name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install pip
      run:  /usr/bin/python3 -m pip install --upgrade pip

    - name: Install setuptools
      run:  /usr/bin/python3 -m pip install --upgrade setuptools

    - name: Install Mkdocs
      run:  /usr/bin/python3 -m pip install --upgrade mkdocs

    - name: Install Minify Plugin
      run:  /usr/bin/python3 -m pip install --upgrade mkdocs-minify-plugin

    - run: git fetch -p

    # - name: Deploy to website branch
      # run:  /usr/bin/python3 -m mkdocs gh-deploy -f website/mkdocs.yml -b website

  firebase-deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          ref: website
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install
      - name: Login to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: strategicbehaviors
          expires: 7d
          entryPoint: .
          firebaseToolsVersion: latest
