name: Deploy to Firebase

on:
  push:
    branches:
      - website

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Or your preferred Node.js version

      - name: Install Firebase CLI
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Or your preferred Node.js version
        run: npm install -g firebase-tools

      - name: Login to Firebase
        run: |
          echo "${FIREBASE_TOKEN}" > serviceAccount.json
          firebase login --no-interactive --token serviceAccount.json

      - name: Deploy to Firebase
        run: firebase deploy

env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}